from pathlib import Path

POSTGRES_SCHEMA = (
    Path(__file__).resolve().parents[1]
    / "migrations"
    / "postgres"
    / "001_platform_schema.sql"
)


def test_postgres_schema_contains_platform_domain_and_postgres_types():
    sql = POSTGRES_SCHEMA.read_text(encoding="utf-8")

    required_tables = {
        "platform_organizations",
        "platform_members",
        "platform_points",
        "platform_point_access",
        "platform_point_rates",
        "platform_member_rates",
        "platform_subscriptions",
        "platform_owner_codes",
        "platform_invites",
        "platform_finance_entries",
        "platform_audit_events",
        "platform_automation_settings",
        "platform_notification_log",
        "platform_subscription_notification_log",
        "platform_rate_limits",
        "platform_schema_migrations",
    }
    assert all(f"CREATE TABLE IF NOT EXISTS {table}" in sql for table in required_tables)
    assert "GENERATED BY DEFAULT AS IDENTITY" in sql
    assert "TIMESTAMPTZ" in sql
    assert "JSONB" in sql
    assert "AUTOINCREMENT" not in sql.upper()
    assert "INSERT INTO platform_schema_migrations" in sql
    assert "VALUES (1), (2)" in sql
