-- PostgreSQL target schema for the platform domain.
-- The Flask/SQLite adapter remains the transition runtime until the repository
-- implementation is switched over and data is verified on staging.

CREATE TABLE IF NOT EXISTS platform_schema_migrations (
    version INTEGER PRIMARY KEY,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS platform_organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_web_user_id BIGINT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    staff_registration_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS platform_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES platform_organizations(id) ON DELETE CASCADE,
    web_user_id BIGINT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('owner', 'manager', 'employee')),
    created_at TIMESTAMPTZ NOT NULL,
    UNIQUE (organization_id, web_user_id)
);

CREATE TABLE IF NOT EXISTS platform_points (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES platform_organizations(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    address TEXT NOT NULL DEFAULT '',
    telegram_chat_id BIGINT UNIQUE,
    telegram_chat_title TEXT NOT NULL DEFAULT '',
    work_time_start CHAR(5) NOT NULL DEFAULT '09:00',
    work_time_end CHAR(5) NOT NULL DEFAULT '18:00',
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'paused')),
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS platform_point_access (
    organization_id BIGINT NOT NULL REFERENCES platform_organizations(id) ON DELETE CASCADE,
    web_user_id BIGINT NOT NULL,
    point_id BIGINT NOT NULL REFERENCES platform_points(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (web_user_id, point_id)
);

CREATE TABLE IF NOT EXISTS platform_point_rates (
    organization_id BIGINT NOT NULL REFERENCES platform_organizations(id) ON DELETE CASCADE,
    point_id BIGINT PRIMARY KEY REFERENCES platform_points(id) ON DELETE CASCADE,
    amount_minor BIGINT NOT NULL CHECK (amount_minor >= 0),
    updated_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS platform_member_rates (
    organization_id BIGINT NOT NULL REFERENCES platform_organizations(id) ON DELETE CASCADE,
    point_id BIGINT NOT NULL REFERENCES platform_points(id) ON DELETE CASCADE,
    member_web_user_id BIGINT NOT NULL,
    amount_minor BIGINT NOT NULL CHECK (amount_minor >= 0),
    visibility TEXT NOT NULL CHECK (visibility IN ('personal', 'hidden')),
    updated_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (point_id, member_web_user_id)
);

CREATE TABLE IF NOT EXISTS platform_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL UNIQUE REFERENCES platform_organizations(id) ON DELETE CASCADE,
    plan TEXT NOT NULL DEFAULT 'control',
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'active', 'grace', 'expired')),
    point_limit INTEGER NOT NULL DEFAULT 1 CHECK (point_limit > 0),
    current_period_end TIMESTAMPTZ,
    grace_until TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS platform_owner_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_hash CHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ,
    used_at TIMESTAMPTZ,
    used_by_user_id BIGINT,
    code_plan TEXT,
    code_point_limit INTEGER CHECK (code_point_limit IS NULL OR code_point_limit > 0),
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS platform_invites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES platform_organizations(id) ON DELETE CASCADE,
    contact TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('manager', 'employee')),
    token_hash CHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    accepted_at TIMESTAMPTZ,
    accepted_by_user_id BIGINT,
    created_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS platform_finance_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES platform_organizations(id) ON DELETE CASCADE,
    point_id BIGINT NOT NULL REFERENCES platform_points(id) ON DELETE CASCADE,
    kind TEXT NOT NULL CHECK (kind IN ('income', 'expense')),
    category TEXT NOT NULL,
    amount_minor BIGINT NOT NULL CHECK (amount_minor >= 0),
    period_month CHAR(7) NOT NULL,
    note TEXT NOT NULL DEFAULT '',
    source TEXT NOT NULL DEFAULT 'manual',
    created_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS platform_audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES platform_organizations(id) ON DELETE CASCADE,
    actor_user_id BIGINT NOT NULL,
    action TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id BIGINT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS platform_automation_settings (
    organization_id BIGINT PRIMARY KEY REFERENCES platform_organizations(id) ON DELETE CASCADE,
    preset TEXT NOT NULL DEFAULT 'standard',
    settings_json JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS platform_notification_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES platform_organizations(id) ON DELETE CASCADE,
    role TEXT NOT NULL CHECK (role IN ('owner', 'manager', 'employee')),
    recipient_user_id BIGINT NOT NULL,
    period_start DATE NOT NULL,
    claimed_at TIMESTAMPTZ NOT NULL,
    UNIQUE (organization_id, role, recipient_user_id, period_start)
);

CREATE TABLE IF NOT EXISTS platform_subscription_notification_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES platform_organizations(id) ON DELETE CASCADE,
    notification_type TEXT NOT NULL,
    period_end TIMESTAMPTZ NOT NULL,
    claimed_at TIMESTAMPTZ NOT NULL,
    UNIQUE (organization_id, notification_type, period_end)
);

CREATE TABLE IF NOT EXISTS platform_rate_limits (
    bucket_key CHAR(64) PRIMARY KEY,
    window_started BIGINT NOT NULL,
    attempts INTEGER NOT NULL CHECK (attempts >= 0)
);

CREATE INDEX IF NOT EXISTS idx_platform_points_org ON platform_points(organization_id);
CREATE INDEX IF NOT EXISTS idx_platform_point_access_org_user
    ON platform_point_access(organization_id, web_user_id);
CREATE INDEX IF NOT EXISTS idx_platform_finance_org_month
    ON platform_finance_entries(organization_id, period_month);
CREATE INDEX IF NOT EXISTS idx_platform_member_rates_org
    ON platform_member_rates(organization_id, member_web_user_id);
CREATE INDEX IF NOT EXISTS idx_platform_audit_org_created
    ON platform_audit_events(organization_id, created_at DESC);

INSERT INTO platform_schema_migrations (version)
VALUES (1), (2)
ON CONFLICT (version) DO NOTHING;
